## Generated by dust2 (version 0.3.5) - do not edit
packmalaria <- structure(
  function() get("packmalaria"),
  class = "dust_system_generator",
  name = "packmalaria",
  package = "packmalaria",
  path = NULL,
  parameters = data.frame(
    name = c("N", "I0", "beta", "gamma"),
    type = c("real_type", "real_type", "real_type", "real_type"),
    constant = c(FALSE, FALSE, FALSE, FALSE),
    required = c(FALSE, FALSE, FALSE, FALSE),
    rank = c(0L, 0L, 0L, 0L)),
  properties = list(
    time_type = "continuous",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = NULL)
